# Generated by Django 5.2.15 on 2026-06-15 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_file_name', models.CharField(max_length=255)),
                ('import_timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.IntegerField(default=0)),
                ('accepted_rows', models.IntegerField(default=0)),
                ('flagged_rows', models.IntegerField(default=0)),
                ('rejected_rows', models.IntegerField(default=0)),
                ('health_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group')),
            ],
            options={
                'verbose_name_plural': 'Import Batches',
                'ordering': ['-import_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ImportReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.JSONField(help_text='Detailed metrics and summary of this import session')),
                ('report_markdown', models.TextField(help_text='Pre-formatted markdown of the Import Report deliverable')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='expenses.importbatch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_row_json', models.JSONField(help_text='Original string key-value pairs from CSV row')),
                ('parsed_row_json', models.JSONField(blank=True, help_text='Parsed fields with resolved types', null=True)),
                ('import_status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], default='ACCEPTED', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='expenses.importbatch')),
            ],
            options={
                'ordering': ['batch', 'row_number'],
                'unique_together': {('batch', 'row_number')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount_original', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency_original', models.CharField(default='INR', max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1.0, max_digits=18)),
                ('amount_base', models.DecimalField(decimal_places=2, help_text='amount_original * exchange_rate', max_digits=18)),
                ('expense_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_settlement_hidden', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to='groups.groupmembership')),
                ('import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='expenses.importrow')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Settlement amount in base currency', max_digits=18)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_received', to='groups.groupmembership')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements_paid', to='groups.groupmembership')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact Amount'), ('PERCENTAGE', 'Percentage'), ('SHARE', 'Share Based')], default='EQUAL', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, help_text='e.g. percentage, share count, or exact amount', max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, help_text='Split amount in base currency', max_digits=18)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='groups.groupmembership')),
            ],
            options={
                'unique_together': {('expense', 'member')},
            },
        ),
    ]
