# Generated by Django 5.2.15 on 2026-06-15 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(choices=[('DUPLICATE_EXPENSE', 'Duplicate Expense'), ('NEGATIVE_AMOUNT', 'Negative Amount'), ('INVALID_DATE', 'Invalid Date'), ('MEMBERSHIP_CONFLICT', 'Membership Conflict'), ('SETTLEMENT_AS_EXPENSE', 'Settlement Recorded as Expense'), ('CURRENCY_ISSUE', 'Currency or Exchange Rate Issue'), ('SPLIT_SUM_MISMATCH', 'Split Sum Mismatch'), ('UNKNOWN_MEMBER', 'Unknown Member'), ('MISSING_PAYER', 'Missing Payer')], max_length=50)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_action', models.CharField(blank=True, help_text='e.g. MERGED, IGNORED, CONVERTED_TO_SETTLEMENT, CORRECTED', max_length=50)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('extra_data', models.JSONField(blank=True, help_text='Stores additional diagnostic info (e.g. competing row IDs, rate values)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Audit Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DecisionTrail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='e.g. MERGED_DUPLICATES, CONVERTED_SETTLEMENT, IGNORED_TIMELINE_CONFLICT', max_length=100)),
                ('target_object_type', models.CharField(help_text='e.g. Expense, AuditAnomaly, GroupMembership', max_length=100)),
                ('target_object_id', models.CharField(help_text='ID or UUID of the target object', max_length=255)),
                ('reasoning', models.TextField(help_text='Detailed user explanation for why this choice was made')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
